### ISSUE TITLE
Query all subcollection documents

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/membrane#120]
Currently, most SDKs only allow querying of subcollection documents when the parent document ID is known. We should design a solution for querying all subcollection documents (e.g. all landmarks in all cities). I believe the Java SDK has an initial implementation, but it needs more discussion.

**Comment by medgar-nitric** [comment]
We should probably add tickets to the other SDK to implement this.

**Comment by medgar-nitric** [comment]
https://github.com/nitrictech/docs/issues/52

**Comment by tjholm** [comment]
closing in favor of tickets raised against each SDK.
