### ISSUE TITLE
Failed to make membrane

### ISSUE THREAD

**Issue by nanikjava** [nitrictech/membrane#70]
**Describe the bug**
Checked out  the project and tried to build it using `make membrane` and got the following error

```
installing go dependencies
Building Go Project...
adapters/grpc/auth_grpc.go:20:2: no required module provides package github.com/nitric-dev/membrane/interfaces/nitric/v1; to add it:
        go get github.com/nitric-dev/membrane/interfaces/nitric/v1
pluggable_membrane.go:24:2: no required module provides package github.com/nitric-dev/membrane/plugins/sdk; to add it:
        go get github.com/nitric-dev/membrane/plugins/sdk
make: *** [makefile:3: membrane] Error 1
````

it's missing `/sdk` inside `plugins` directory  ?

**Comment by jyecusch** [comment]
Hi @nanikjava, thanks for raising this, it looks like we've left an older build target in the makefile. We'll get that cleaned up, in the meantime, you can try one of these depending on which platform you're building for:

## Binary for local run

`make dev-static`

## Docker image for local run

`make dev-docker`

You should be able to substitute `dev` for `aws`, `gcp`, or `do` to target AWS, Google Cloud or DigitalOcean for the builds also.

**Comment by nanikjava** [comment]
Thanks @jyecusch 

Tried your suggestion to build binary for local run and got the following error

```
└─ $ ▶ make dev-static
Generating Proto Sources
./contracts/proto: warning: directory does not exist.
./contracts/proto/*/**/*.proto: No such file or directory
make: *** [makefile:67: generate-proto] Error 1
```

**Comment by jyecusch** [comment]
The contents of the `/contracts` directory contain protobuf contracts, which we include as a git submodule. Can you try `git submodule init` from the root of the project?

**Comment by jyecusch** [comment]
Apologies, I mean `git submodule update --init --recursive`

**Comment by jyecusch** [comment]
Also, if you're just getting started you can skip the build step for the Membrane by building a project with our [CLI](https://nitric.io/docs/nitric-cli). It will use Docker to pull pre-built images for targeted environments.

**Comment by nanikjava** [comment]
> Apologies, I mean `git submodule update --init --recursive`

Yes, this works able to compile `membrane`

I'm interested to learn the internals of the `membrane` server, trying to look into the code inside IDE too :)

When running `membrane`, got the following

```
└─ $ ▶ ./membrane
mkdir /nitric: permission denied
2021/07/06 12:13:02 There was an error initialising the membraneServer server: Missing membrane plugins, if you meant to load with missing plugins set options.TolerateMissingServices to true
```

didn't see any `--help` option for `membrane` though ?

**Comment by nanikjava** [comment]
> Also, if you're just getting started you can skip the build step for the Membrane by building a project with our [CLI](https://nitric.io/docs/nitric-cli). It will use Docker to pull pre-built images for targeted environments.

I'm interested to learn the internals of the `membrane` server, trying to look into the code inside IDE too :)

**Comment by jyecusch** [comment]
At the moment, the Membrane isn't really intended to run outside of a container, so that error you're seeing is it trying to access a directory it expects to exist. We need to make that configurable, I'll add another issue for that. Happy to answer questions about the server is general though as you have them.

**Comment by jyecusch** [comment]
Created #71 to deal with the local run issue mentioned.
