### ISSUE TITLE
Unable to dial http worker

### ISSUE THREAD

**Issue by nanikjava** [nitrictech/membrane#74]
Was able to run `membrane` using the following parameter

`LOCAL_DB_DIR=/home/myself/membrane;MEMBRANE_MODE=HTTP_FAAS`

but  getting error 

`Membrane Error: Unable to dial http worker, does it expose a http server at: 127.0.0.1:8080?, exiting`

Stepping through the code can see the error is thrown from inside this code:

`worker.NewFaasHttpWorker(s.childAddress)`

seems like it is waiting to connect to something on port `8080` but no clue what it is trying to connect to ?

Are there any services that need to be run from the code that runs on port `8080`

**Comment by jyecusch** [comment]
The Membrane expects to sit in front of a server/service of some kind and act as an adapter for incoming requests for that service. For example, a message from an AWS SNS topic or a Google PubSub topic would come to the Membrane first, it translates them into a standard 'Trigger' format and passes them on. It also works for HTTP requests.

The thing it's waiting for on port 8080 is the service you want to run behind the membrane to process those triggers. Our SDKs provide methods to start a service on that port by default and handle incoming requests with a standard function in the SDK language. If you're using Go, check out the [Go SDK](https://github.com/nitrictech/go-sdk). If you want an even easier setup we provide 'Templates' for those services, which you can read about [here](https://nitric.io/docs/services).

If you're only interested in the Membranes services and don't want it to handle requests we can look at supporting that, it should be an easy change.

**Comment by nanikjava** [comment]
I'm sure it's just me and I'm using Nitric the wrong way, but do let me know which part I'm not doing it right  :) 

Tried following the step from https://nitric.io/docs/quick-start and able to run it and run the service and able to access the service via curl, this is all good.

Now, tried running it separately so run `membrane` first and it works, then run below sample app

```
package main

import "github.com/nitrictech/go-sdk/faas"

// NitricFunction - Handles individual function requests (http, events, etc.)
func NitricFunction(trigger *faas.NitricTrigger) (*faas.NitricResponse, error) {
	// Do something interesting...
	response := trigger.DefaultResponse()
	response.SetData([]byte("Hello Nitric"))

	return response, nil
}

func main() {
	faas.Start(NitricFunction)
}
```



Running `membrane` still get the error

`Membrane Error: Unable to dial http worker, does it expose a http server at: 127.0.0.1:8080?, exiting`

Going through the sample code and found that inside the `StartWithClient` function it is able to send msg to `membrane` but then after that it stops (probably because `membrane` has exited)

Does this mean that there still need to be an app that is running accepting connection on port `8080`, is there a sample app that I can try.

**Comment by tjholm** [comment]
Hi @nanikjava, are you still running the membrane in `HTTP_FAAS` mode?

If you're trying to run the same app above, this will be running in our default `FAAS` mode, which utilises gRPC and the client initiates the connection with the membrane. The current documentation on the membrane modes is out of date and I'll need to update it. If you're curious what modes each runtime we support uses you can have a look at our template repositories: 

- https://github.com/nitrictech/function-templates
- https://github.com/nitrictech/server-templates

Currently the membrane is started with args that tell the membrane process the child process to spawn.
`membrane <command to run>`

For example assuming the membrane you've built is on `PATH` then you should be able to run this in the working directory for the go application you provided above:
`LOCAL_DB_DIR=/home/myself/membrane; membrane go run main.go`

Let me know if that works for you.

**Comment by nanikjava** [comment]
Thanks for the reply.

Spend more time playing around with it, getting the hang of it now. So what I've done is 

1. Run `membrane`
2. Run the following sample

```
// NitricFunction - Handles individual function requests (http, events, etc.)
func NitricFunction(trigger *faas.NitricTrigger) (*faas.NitricResponse, error) {
	// Do something interesting...
	response := trigger.DefaultResponse()
	response.SetData([]byte("Hello Nitric"))

	return response, nil
}

func main() {
	faas.Start(NitricFunction)
}
```
3. Using curl access the `NitricFunction` via

	`curl http://127.0.0.1:9001`

and was able to get the `Hello Nitric` message.

So there are 2 ways to run the `NitricFunction`:

1) Run it as argument to `membrane`
2) Run `membrane` and then run the application. Though this require the sample app to run quickly otherwise `membrane` will exit with error `Membrane Error: No workers available!, exiting`

**Comment by nanikjava** [comment]
Closing this ticket as issue has been resolved.
