### ISSUE TITLE
Documents - query fetch should also return documents key path 

### ISSUE THREAD

**Issue by medgar-nitric** [nitrictech/membrane#92]
When a document query is performed we should return the documents key path in addition to the content so that developers can perform a edit operation based on the item. A common use case for this is creating an editable grid / table.

Supporting this well in the SDK Document API will need some thought as the existing Doc Reference uses a get() pattern to lazy load the contents.  Having a query return a list of DocRef would be pre-populated with content, would be inconsistent with this design.  

Returning another value type provides both Document content and method to create a DocRef object would probably be the best approach.    

Firestore's approach is to return a ```DocumentSnapshot``` type from query iterators:
```
// A DocumentSnapshot contains document data and metadata.
type DocumentSnapshot struct {
	// The DocumentRef for this document.
	Ref *DocumentRef

	// Read-only. The time at which the document was created.
	// Increases monotonically when a document is deleted then
	// recreated. It can also be compared to values from other documents and
	// the read time of a query.
	CreateTime time.Time

	// Read-only. The time at which the document was last changed. This value
	// is initially set to CreateTime then increases monotonically with each
	// change to the document. It can also be compared to values from other
	// documents and the read time of a query.
	UpdateTime time.Time

	// Read-only. The time at which the document was read.
	ReadTime time.Time

	c     *Client
	proto *pb.Document
}
```

**Comment by tjholm** [comment]
@medgar-nitric 

Just linking this here as a required change for this issue:
https://github.com/nitrictech/contracts/pull/39/files

If you're happy with it, just needs one more approval.
