### ISSUE TITLE
Name Validation for Buckets, Collections, Topics and Secrets 

### ISSUE THREAD

**Issue by medgar-nitric** [nitrictech/membrane#93]
We should add validation for document collection names and storage bucket names to ensure they are portable across cloud vendors.  A strict policy of letters and numbers and leading letter character should maximize portability.  

Note these names are used to derive a filename for Boltdb based plugin services.

We should also look at applying validation rules for topic names.

Research into what the intersection of the cloud vendor validation rules is appropriate.

**Comment by medgar-nitric** [comment]
I think supporting underscores would also be useful, so people can avoid camel case names for readability preferences.

**Comment by tjholm** [comment]
Two places this needs to be supported:
1. As part of stack name definitions: https://github.com/nitrictech/cli/issues/102
2. As part of membrane services: https://github.com/nitrictech/membrane/issues/115

**Comment by jyecusch** [comment]
@tjholm  I think the regex patterns in place in the contracts are good for now. The CLI JSON Schema already match the pattern, so no changes are needed there.

**Comment by tjholm** [comment]
@jyecusch Sounds good, I've removed the contracts change from draft ready for review and merge once that's in will update contracts submodule for membrane onto main and remove the or from draft.
